kind: Pod
apiVersion: v1
metadata:
  name: authz
  labels:
    app: authz
spec:
  containers:
    - name: authz
      image: docker.io/kettil/test-envoy-ext-authz:latest
      env:
        - name: GRPC_PORT
          value: '9000'
      ports:
        - containerPort: 9000
