---
apiVersion: v1
kind: Service
metadata:
  name: authz
  labels:
    app: authz
spec:
  ports:
    - name: grpc
      port: 9000
      targetPort: 9000
  selector:
    app: authz

---
kind: Pod
apiVersion: v1
metadata:
  name: authz
  labels:
    app: authz
spec:
  containers:
    - name: authz
      image: docker.io/kettil/test-envoy-ext-authz:latest
      env:
        - name: GRPC_PORT
          value: '9000'
      ports:
        - containerPort: 9000
