---
apiVersion: v1
kind: Service
metadata:
  name: envoy
  labels:
    app: envoy
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 18000
  selector:
    app: envoy

---
kind: Pod
apiVersion: v1
metadata:
  name: envoy
  labels:
    app: envoy
spec:
  volumes:
    - name: manifest
      configMap:
        name: manifest
    - name: faas-envoy-config
      emptyDir: {}
  containers:
    - name: envoy
      image: docker.io/envoyproxy/envoy-dev:latest
      ports:
        - name: http
          containerPort: 18000
          protocol: TCP
      resources: { }
      volumeMounts:
        - name: faas-envoy-config
          mountPath: /etc/envoy
  initContainers:
    - name: envoy-init
      image: docker.io/kettil/test-envoy-init-container:latest
      env:
        - name: MANIFEST_FILE
          value: /etc/faas/manifest.yaml
        - name: ENVOY_CONFIG_FILE
          value: /etc/envoy/envoy.yaml
      volumeMounts:
        - name: manifest
          mountPath: /etc/faas
        - name: faas-envoy-config
          mountPath: /etc/envoy
