apiVersion: v1
kind: Service
metadata:
  name: invoker
  labels:
    app: invoker
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8002
      targetPort: 8002
  selector:
    app: invoker
