apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- authz-pod.yaml
- authz-service.yaml
- envoy-pod.yaml
- envoy-service.yaml
- fake-invoker-pod.yaml
- fake-invoker-service.yaml

configMapGenerator:
- name: manifest-config
  files:
  - manifest.yaml
