apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: test-envoy-ext-authz
build:
  artifacts:
  - image: docker.io/kettil/test-envoy-ext-authz
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - kube/kustomize
